# The WASM workflow step, built into a folder Immich can load.
#
# Immich reads plugins from SUBDIRECTORIES of IMMICH_PLUGINS_INSTALL_FOLDER, each
# holding manifest.json plus the wasm named by `wasmPath`. So $out is the install
# folder and $out/clip-filter is the plugin.
#
# The manifest itself is generated by plugin/manifest.py, which is where the two
# upstream traps that shape it are documented — read that before changing
# anything here.
{
  lib,
  stdenvNoCC,
  python3,
  extism-js,
  binaryen,
  src,
  # Where the plugin should reach the sidecar, FROM IMMICH'S POINT OF VIEW. This
  # is baked into the manifest twice: as the step's default, and as the
  # `allowedHosts` entry the host checks before it will make the call at all.
  sidecarUrl ? "http://127.0.0.1:8351/classify",
  pluginName ? "clip-filter",
}:

let
  # Both sources, because the .d.ts declares the host-function import — editing
  # it alone changes the compiled wasm just as much as editing the JS. The URL
  # counts too: it is rewritten into the JS at build time.
  buildId = builtins.substring 0 8 (
    builtins.hashString "sha256" (
      builtins.readFile "${src}/plugin.js"
      + builtins.readFile "${src}/plugin.d.ts"
      + sidecarUrl
    )
  );
in
stdenvNoCC.mkDerivation {
  pname = "immich-clip-plugin";
  # The store path carries the build hash even though the manifest's `version`
  # deliberately does not, so `systemctl show immich-server -p Environment` says
  # which build is deployed.
  version = "1.0.0-${buildId}";
  inherit src;

  nativeBuildInputs = [
    python3
    extism-js
    binaryen # extism-js shells out to wasm-merge and wasm-opt
  ];

  dontConfigure = true;

  buildPhase = ''
    runHook preBuild
    export HOME="$TMPDIR"
    substituteInPlace plugin.js \
      --replace 'sidecar: "http://127.0.0.1:8351/classify"' 'sidecar: "${sidecarUrl}"'
    extism-js plugin.js -i plugin.d.ts -o clip_filter.wasm
    python3 manifest.py \
      --sidecar-url '${sidecarUrl}' --name '${pluginName}' \
      --build-id '${buildId}' > manifest.json
    runHook postBuild
  '';

  installPhase = ''
    runHook preInstall
    install -Dm444 clip_filter.wasm "$out/${pluginName}/clip_filter.wasm"
    install -Dm444 manifest.json    "$out/${pluginName}/manifest.json"
    runHook postInstall
  '';

  meta = {
    description = "CLIP content-filter step for Immich Workflows (WASM plugin)";
    platforms = extism-js.meta.platforms;
    license = lib.licenses.mit;
  };
}
